### ISSUE TITLE
Arrume

### ISSUE THREAD

**Issue by Dowjs** [cookieukw/Clownters#2]
Não está funcionando não sei se está desatualizado, estou usando a versão 118 do termux

**Comment by cookieukw** [comment]
> Não está funcionando não sei se está desatualizado, estou usando a versão 118 do termux 

Eu deixei avisado que este projeto é apenas um fork e que é uma versão antiga. O issue também está bem vago para poder arrumar algo, caso fosse o caso. Tente usar os recursos do projeto original que tem a versão mais recente.

**Comment by Dowjs** [comment]
Qual o username?

**Comment by Dowjs** [comment]
Consegui baixar mas está pedindo username e senha

**Comment by cookieukw** [comment]
Isso é o usuário e senha que um cara disponibiliza em grupos do WhatsApp, tem que entrar e procurar. Eu dei fork de uma versão antiga que não pede isso, que no caso, é essa. Além de fazer algumas alterações no bash.
